### PR TITLE
Create a PR workflow using Github Actions

### PR DESCRIPTION
**Pull request by boaz0**
Moving from Travis-CI to Github Actions

Why?

- Easy to control the flow for testing/linting/building
- Easy to extend - adding different workflows when updating PR, adding comments and etc
- Many actions that are not available on Travis-CI
- Travis CI can be used as a Github Action

TODO
- [ ] Need to figure out why we are running the bootstrap.sh script?
- [ ] Build the UI as part of the CI workflow

### CODE REVIEW

**Comment by boaz0** [comment]
This is a test

**Comment by dlabrecq** [comment]
FYI @adberglund @chambridge

**Comment by dlabrecq** [comment]
FYI @adberglund @chambridge @lcouzens

**Comment by boaz0** [comment]
Unfortunately, I couldn't figure out a way to test Github Actions and learn about it unless I opened this PR (and unset it to draft). I am keeping this open to learn more about Github Actions and see how to use it to do more than CI builds. Please don't merge this or close this. Thanks.

**Comment by dlabrecq** [comment]
If just learning, couldn't you create your own private project? I'm concerned that testing Github Actions here may have an unintentional affect on this workspace.

**Comment by boaz0** [comment]
Yeah maybe I'll try that...

**Pull request closed without merging**
