### PR TITLE
Add unit tests to tabs

### PR DESCRIPTION
**Pull request by boaz1337**

### CODE REVIEW

**Comment by dlabrecq** [comment]
Deploy preview for *project-koku* ready!

Built with commit 97979bdf8867a9f5b3e67c9051e7434017e34dd5

https://deploy-preview-105--project-koku.netlify.com

**Comment by boaz1337** [comment]
Yeah, I thought about it too. 
Let's speak about it offline.

**Comment by boaz1337** [comment]
@dlabrecq - I hope I didn't get too far but I think I found a better way to test without snapshot. WDYT?

**Comment by dlabrecq** [comment]
I'm all for a better way. My thought was we should avoid relying on snapshots and use more traditional unit testing.

**Comment by boaz1337** [comment]
great then you probably will love this change (no snapshot, only verifying through `props` and `text`). would you mind reviewing it?

**Pull request merged**
