### PR TITLE
feat(costmodels): add link to documents in wizard

### PR DESCRIPTION
**Pull request by boaz0**
image

//cc @dayleparker @nlcwong

### CODE REVIEW

**Comment by nlcwong** [comment]
@boaz0 Please do not put the learn more in the step title. It should be on the same line as where the introductory text would be located.

**Comment by dlabrecq** [comment]
Is there an issue we can connect this with for QA testing?

**Comment by boaz0** [comment]
@nlcwong where is the introductory text is located in the screenshot?

**Comment by nlcwong** [comment]
CreatePriceList-Step1

**Comment by nlcwong** [comment]
@boaz0 just making sure that this Learn more link is going to here: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/using_cost_models/configuring-cost-models

**Comment by boaz0** [comment]
@nlcwong done
image

**Comment by nlcwong** [comment]
As long as the padding is inline with the Add sources wizard, then I'm OK for now.  We might need to open a new bug later to figure out what the correct padding should be for wizard contents.  Will need a visual designer to help with that and more than likely that'll be something that is CRC wide.

**Pull request merged**
