### PR TITLE
Login: Removed the typings workaround for the PF4 AlertVariant

### PR DESCRIPTION
**Pull request by dlabrecq**
Removed the typings workaround in the login page for the PF4 AlertVariant. This type issue has since been fixed in PF4.

### CODE REVIEW

**Comment by dmiller9911** [comment]
Deploy preview for *koku* ready!

Built with commit 19ecf83d281780ccdb748f76c38fc0ba6335885a

https://deploy-preview-94--koku.netlify.com

**Comment by dlabrecq** [comment]
Deploy preview for *project-koku* ready!

Built with commit 19ecf83d281780ccdb748f76c38fc0ba6335885a

https://deploy-preview-94--project-koku.netlify.com

**Comment by chambridge** [comment]
Seems a bit strange that the Alert says "Danger" when the user could have just mistyped their password.

image

**Comment by boaz1337** [comment]
LGTM :+1:

**Comment by dlabrecq** [comment]
Thanks for the review. I'll merge and work on updating PF4 in order to get rid of the "Danger" text

**Pull request merged**
