### PR TITLE
fix(onboarding): realign spaces and indentations in checkboxes

### LINKED ISSUE #869: Bad text fomatting on OCP add source modal
**Describe the bug**
Bad text fomatting on add source modal

**To Reproduce**
1. Go to 'sources'
2. Click on 'add a source'
3. Select ocp and click next
4. See formatted bullet points

**Expected behavior**
There should be even spaces between text plus bullet points should be tabbed in

**Screenshots**
Screenshot from 2019-05-14 10-48-16

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser FireFox
 - Version 66

### PR DESCRIPTION
**Pull request by boaz0**
closes #869 

Screenshot_2019-05-16 Cost Management

//cc @dchorvat1

### CODE REVIEW

**Comment by lcouzens** [comment]
@boaz0 I wonder whether having a space between the first two lines might look nicer too. What do you guys think?
Screenshot from 2019-05-16 16-20-22

**Comment by boaz0** [comment]
@lcouzens 

how about now?

Screenshot_2019-05-16 Cost Management

**Comment by lcouzens** [comment]
That looks SWEEETT!! Good job!

**Comment by boaz0** [comment]
Thanks @lcouzens for your help
Thanks @dlabrecq for your review

**Pull request merged**
