### PR TITLE
 fix(overview): fix overlapping grid columns in firefox

### PR DESCRIPTION
**Pull request by mcoker**
Fixes https://github.com/project-koku/koku-ui/issues/173

I put a fix in PF4 core for this, and added that fix to the global css here.

This includes https://github.com/project-koku/koku-ui/pull/268, so it should be merged after that PR.

### CODE REVIEW

**Comment by dlabrecq** [comment]
Looks like there are changes from https://github.com/project-koku/koku-ui/pull/268 included in this PR. I can't really tell what's changed?

**Comment by mcoker** [comment]
It's just so there wouldn't be any conflicts from #268 since this also touches global.css

It's the addition of lines 19-23 in global.css

```
.pf-l-grid > *,
.pf-l-grid .pf-l-grid__item {
  min-height: 0;
  min-width: 0;
}
```

**Comment by dlabrecq** [comment]
Maybe you can try rebasing? This PR shows there are 7 files that have changed.

**Comment by mcoker** [comment]
@dlabrecq rebased

**Pull request merged**
