### PR TITLE
Updating to use a single esi tag in index.html

### PR DESCRIPTION
**Pull request by ryelo**
This change is needed after: https://github.com/RedHatInsights/insights-chrome/pull/150

### CODE REVIEW

**Comment by chambridge** [comment]
Don't merge this until after the 10-12 demo please.

**Comment by ryelo** [comment]
@dlabrecq we haven't released the newest version of chrome to stable. This is going to work with the beta version of chrome.

**Comment by dlabrecq** [comment]
I saw the Slack comment about "insights-chrome is updated on all 3 stable environments". The change appears to be working now.

Should we also update the title per the suggestion below? I can create another PR if you prefer?

```
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <title>Red Hat Insights | Cost Management </title>
        <esi:include src="/@@insights/static/chrome/snippets/head.html"/>
    </head>
    <body>
        <esi:include src="/@@insights/static/chrome/snippets/body.html"/>
    </body>
</html>
```

**Comment by ryelo** [comment]
@dlabrecq Ah. Yes. That would be great. As long as it's working, that's the biggest factor!

**Pull request merged**
