### PR TITLE
Add AWS and OCP dashboard tabs

### PR DESCRIPTION
**Pull request by dlabrecq**
Adds AWS and OCP tabs. Creates a new overview & ocpDashboard pages. Renames the old dashboard as awsDashboard.

Pages:
- overview
- awsDashboard
- awsDetails
- ocpDashboard
- ocpDetails

Note that the OCP pages are just copies with some minor text changes.

Fixes https://github.com/project-koku/koku-ui/issues/169

### CODE REVIEW

**Comment by dlabrecq** [comment]
Deploy preview for *project-koku* ready!

Built with commit 063267f763a8357ca2662e72377411843dd15c7e

https://deploy-preview-188--project-koku.netlify.com

**Comment by chambridge** [comment]
I currently get the following errors when running the branch:
```
Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at eval (TextContent.js:31)
    at Module../node_modules/@patternfly/react-core/dist/esm/components/Text/TextContent.js (vendors~aws~home~ocp~providersModal.bundle.js:1391)
    at __webpack_require__ (main.bundle.js:785)
    at fn (main.bundle.js:148)
    at eval (index.js:2)
    at Module../node_modules/@patternfly/react-core/dist/esm/components/Text/index.js (vendors~aws~home~ocp~providersModal.bundle.js:1427)
    at __webpack_require__ (main.bundle.js:785)
    at fn (main.bundle.js:148)
    at eval (index.js:137)
    at Module../node_modules/@patternfly/react-core/dist/esm/components/index.js (vendors~aws~home~ocp~providersModal.bundle.js:1511)
```
and
```
Uncaught TypeError: Cannot read property 'secondary' of undefined
    at ProxyComponent.render (providersModal.tsx:149)
    at ProxyComponent.hotComponentRender (react-hot-loader.development.js:622)
    at ProxyComponent.proxiedRender (react-hot-loader.development.js:637)
    at finishClassComponent (react-dom.development.js:13193)
    at updateClassComponent (react-dom.development.js:13155)
    at beginWork (react-dom.development.js:13824)
    at performUnitOfWork (react-dom.development.js:15863)
    at workLoop (react-dom.development.js:15902)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
```

**Comment by dlabrecq** [comment]
@chambridge That error is due to stale PF4 packages. If you remove your node_modules directory and perform a clean `yarn install`, those errors should go away.

**Comment by chambridge** [comment]
yep, that worked.

**Pull request merged**
