### PR TITLE
PatternFly milestone update

### PR DESCRIPTION
**Pull request by dlabrecq**
Update PatternFly milestone and @redhat-cloud-services packages

https://issues.redhat.com/browse/COST-2908

### CODE REVIEW

**Comment by gitdallas** [comment]
snaps need `-u`, chart label ids are formatted differently.

**Comment by gitdallas** [comment]
>

**Review by gitdallas — CHANGES_REQUESTED** [review]
snaps need `-u`, chart label ids are formatted differently. nvm the close/reopen - accidental

**Comment by dlabrecq** [comment]
Updated the snapshots, thanks!

**Review by gitdallas — APPROVED** [review]

**Pull request merged**
