### PR TITLE
feat(costmodel): render read-only view

### PR DESCRIPTION
**Pull request by boaz0**
related to #1338 

image

image

image

image

### CODE REVIEW

**Comment by boaz0** [comment]
DO NOT MERGE YET... missing unit tests

**Comment by boaz0** [comment]
//cc @nlcwong - are you sure you want to add tooltip to each of the disabled items?

**Comment by nlcwong** [comment]
Yes.  So the plan is that we are going to go ahead with this approach and use it to test it out on our users to see if they get it.  Worse case, they don't get it and we'll need to figure out an alternative, but until that testing (we are thinking "summit" timeframe) let us go with this approach.

**Comment by boaz0** [comment]
@nlcwong @dlabrecq - there is a problem to get tooltips into dropdown items because it wraps the component inside "disabled" item. So it's not perfect but it's better than nothing.

Screenshot from 2020-03-12 11-26-17

Screenshot from 2020-03-12 11-26-26

Screenshot from 2020-03-12 11-27-24

**Comment by dlabrecq** [comment]
Do we really want disabled tooltips on individual dropdown options? IMO, no.

Currently, we don't show tooltips for enabled dropdown options, nor does PatternFly demo a pattern in their examples.

**Comment by nlcwong** [comment]
Boaz,
Does all the items in the drop down need to be disabled for that tooltip to
appear or just one?  I'll forward this to Margot and Kendra to figure this
out from the RH Cloud perspective.

Dan,
I get your concern and Matt Carrano has the same concern w/r/t discovery
and whether or not this should be a PF guidance.  The game plan is to go
ahead with the tooltip and test with users.  The RBAC team is having the
same issues and actually this whole disabled thing was born out of that
discussion.  I know Kendra is trying to start a thread going to find more
use cases from the other products on how they are handling things and will
work with Matt Carrano to get an official guidance on this.  Until then,
we're going to go ahead with the disabled button tooltip approach since
that feels the simplest (since launching a dialog that is a notification
would be more involved) and we want to test something out.

- Natalie

NATALIE WONG

SENIOR UX INTERACTION DESIGNER

Red Hat <https://www.redhat.com/>

300 A Street, Boston, MA 02210

nwong@redhat.com    T: +1-857-770-0627    M: +1-508-963-6144
<https://red.ht/sig>

**Comment by dlabrecq** [comment]
I'm ok with the disabled button, but strongly against adding this to individual dropdown options.

**Comment by boaz0** [comment]
Found a workaround

Screenshot from 2020-03-17 00-02-37

Screenshot from 2020-03-17 00-02-50

**Comment by nlcwong** [comment]
MIND BLOWN!

**Pull request merged**
