### PR TITLE
118 insights ui integration

### PR DESCRIPTION
**Pull request by chambridge**
@dlabrecq @boaz1337 Wanted to share where I was with the Insights UI integration.

- README updated with proxy instructions
- SPANDX config provided for API workaround
- PublicPath and router updates to satisfy proxy setup
- Added needed integration packages.

### CODE REVIEW

**Comment by chambridge** [comment]
Current issues being worked:
- CSS problem bumping react-core & others was suppose to fix, but still investigating
- getProvider() calls endlessly
- Error when Sort is added in Toolbar "Uncontrolled Dropdown"

**Comment by dlabrecq** [comment]
Deploy preview for *project-koku* ready!

Built with commit 1069afc2672757d8b34de0a3eb67bbb6061fb635

https://deploy-preview-151--project-koku.netlify.com

**Comment by chambridge** [comment]
If you have time please walk through the setup, let me know if it makes sense.

FYI - The insights team will begin work in the insights-chrome project next week that will flow authorization on API calls so there will be a tweak there which will remove the current user/password need.

**Comment by chambridge** [comment]
I believe the latest set of changes fixes all of the known issues and pulls in latest changes from master.

**Comment by chambridge** [comment]
@boaz1337 Agree, but I know the Insights UI team is aware of that and the secondary navigation issues and are working to fix/improve them.

**Pull request merged**
