### PR TITLE
allow proxying stage envs

### PR DESCRIPTION
**Pull request by redallen**
Allows proxying to https://cloud.stage.redhat.com/ or https://console.stage.redhat.com/ assuming your system-wide proxy is configured.

Closes https://issues.redhat.com/browse/RHCLOUD-14975

### CODE REVIEW

**Review by dlabrecq — APPROVED** [review]

**Review by dlabrecq — CHANGES_REQUESTED** [review]
I could not reach https://stage.foo.redhat.com:1337/beta/openshift/cost-management/ locally using our start target.

Is there something I did wrong?

**Comment by redallen** [comment]
Yes, you need to also have a system-wide proxy.pac file configured per the new Akamai "pre-prod lockdown": https://source.redhat.com/groups/public/akamai/wiki/akamai_pre_prod_lockdown

**Comment by ddonahue007** [comment]
Running into the following when on Mac OS, this is after updated the system wide proxy.

Screen Shot 2021-07-22 at 1 18 30 PM

**Comment by redallen** [comment]
Updated. You should no longer need the system-wide proxy.

**Comment by dlabrecq** [comment]
Hey Zack, I did some testing and was able to view Cost Management on stage and stage-beta.
However, I'm not able to create a cost model. Nor am I able to change the "distribution type" of an existing cost model.

Our cost model wizard (and "distribution type" dialog) calls the https://stage.foo.redhat.com:1337/api/cost-management/v1/cost-models/ API, which generates a 403 error.

When I go directly to https://console.stage.redhat.com/beta/openshift/cost-management/cost-models, the API is successful.
Is there anything you can do to proxy the api/cost-management API requests?

**Error 1:**
Screen Shot 2021-07-23 at 6 34 43 PM

**Error 2:**
Screen Shot 2021-07-23 at 6 41 55 PM

**Review by ddonahue007 — APPROVED** [review]
From the testing I have done so far it looks good. Lets wait for @dlabrecq to finish hist testing as I might have missed some corner cases.

**Review by dlabrecq — APPROVED** [review]
This seems to be working now. Thanks for hanging in there, Zack

**Pull request merged**
