### PR TITLE
fix(costmodels): allow for $0 rate

### PR DESCRIPTION
**Pull request by boaz0**
do not merge before https://github.com/project-koku/koku/pull/2543

closes COST 833

### CODE REVIEW

**Review by dlabrecq — APPROVED** [review]

**Comment by dlabrecq** [comment]
Is this still a work in progress? Please let me know when ready and I'll review

**Comment by boaz0** [comment]
This is in "draft" because I am waiting on Doug's PR to be merged.
Maybe I will move it to "Ready for review" and just add "DONT MERGE" tag.

**Review by dlabrecq — APPROVED** [review]

**Comment by dccurtis** [comment]
@boaz0 sorry for the delay in merging!  API change is done

**Comment by boaz0** [comment]
Merged! Thank you all!

**Pull request merged**
